#+OPTIONS: toc:nil -:nil H:6 ^:nil
#+EXCLUDE_TAGS: noexport
#+BEGIN_EXAMPLE
---
title: "Copyright"
layout: notation
description:
path: "/copyright/"
---
#+END_EXAMPLE

#+BEGIN_QUOTE
  Royalty Free Sounds

  Royalty Free Sounds are sounds that are free from royalties. They can
  be used commercially in things like movies, games, and anything else
  you might need a cool sound for. You may not however redistribute them
  for a profit. While sending one to a friend is ok, selling one to a
  customer is not. Creative Commons Attribution 3.0

  Creative Commons Attribution 3.0 is one of many CC Audio types.
  Creative Commons Attribution 3.0 put simply means you can use this
  audio but you must attribute your work to this person. If the audio is
  from Mike Koenig then you need to give him credit somewhere. That
  somewhere could be in the credits, the cd cover, or a link to the
  sounds page from your site. Public Domain Sounds

  Public Domain Sounds are sounds that have been added to the public
  domain. They are owned by the public, and are 100% free. Items get
  added to the PD in a variety of different ways. 1.) Items older than
  the public domain age setting are automatically added. 2.)Thoughtful
  members of the audio community donate their own works for the good of
  others. 3.) Speeches by presidents and other political audio is
  usually considered public domain works.
#+END_QUOTE

from
[http://soundbible.com/royalty-free-sounds-1.html#creativecommonssounds]

[[https://www.gnu.org/gnu/thegnuproject.html][The GNU Project]]
