#Jekyll config file

# Setup
name: Grant Surratt
author: Grant Surratt
title: Sunflower Sea Star
tagline: Grep and grok.
description: Grep and grok.
url: https://sunflowerseastar.com
baseurl: ""

#files to exclude, array
exclude:
  - README.md
  - __reference

# Syntax highlighting
#highlighter:         pygments

# Permalinks
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

#twitter_username: cozywigwam
github_username:  cozywigwam

# Build settings
markdown: kramdown

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          assets/styles
  style:            :compressed


# GitHub Pages configuration overrides
# https://help.github.com/articles/using-jekyll-with-pages/#configuration-overrides
safe: true
lsi: false
#source: [your top-level directory]