# Jekyll config file
# defaults: https://jekyllrb.com/docs/configuration/#default-configuration

# Setup
name: Grant Surratt
author: Grant Surratt
title: Sunflower Sea Star
tagline: Grep and grok.
description: Grep and grok.
url: http://sunflowerseastar.com
timezone: America/San_Francisco

collections:
  notations:
    output: true


#files to exclude, array
exclude:
  - README.md
  - __reference

# Permalinks
permalink: pretty

twitter_username: cozywigwam
github_username: cozywigwam

liquid:
  error_mode: strict

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: assets/styles
  style: :compressed


# GitHub Pages configuration overrides
# https://help.github.com/articles/using-jekyll-with-pages/#configuration-overrides
safe: true
