#+OPTIONS: toc:nil -:nil H:6 ^:nil
#+EXCLUDE_TAGS: noexport
#+BEGIN_EXAMPLE
---
title: "Markup"
layout: notation
description: Crosshatch
path: "/markup/"
---
#+END_EXAMPLE

* Basics

#+BEGIN_EXAMPLE
| th   | th     | th    |
| :--- | :---:  | ---:  |
| left | middle | right |

*italics*, _alt italics_

**bold**, __alt bold__

***bold italic***, ___alt bold italic___

> quote

~~strike through~~

`code`

[site](example.com)
#+END_EXAMPLE

[[https://johnmacfarlane.net/babelmark2/][Babelmark 2]] by [[https://johnmacfarlane.net/babelmark2/][John MacFarlane]]

Babelmark "What is this for?":

#+BEGIN_QUOTE
This is a tool for comparing the output of various implementations of John Gruber’s markdown syntax for plain text documents. The official markdown syntax documentation is silent or vague on many issues, and implementations have diverged in their interpretations of the syntax. Even when the interpretation of the syntax spec is not in question, implementations may have bugs. So it is useful to be able to see at a glance how implementations differ on various inputs. The hope is that this tool will promote discussion of how and whether certain vague aspects of the markdown spec should be clarified.
#+END_QUOTE

* Dialects, variations

| daring fireball          | Slack     | JIRA                    | SO                  |
|--------------------------+-----------+-------------------------+---------------------|
| *italics*, _alt italics_ |           |                         |                     |
| __double underscore__    |           |                         |                     |
| **bold**                 |           |                         |                     |
| ***bold italic***        |           |                         |                     |
| > quote                  | >         | {quote}..{quote}        |                     |
| ~~strike through~~       |           |                         |                     |
| `code`                   | `inline`  | {{inline}}              | `inline`            |
| code block               | backticks | {code}..{code}          | indent              |
| [site](example.com)      | n/a       | [site[pipe]example.com] | [site](example.com) |

** CommonMark

An attempt "to specify Markdown syntax unambiguously."

- [[https://github.com/jgm/CommonMark][CommonMark on GitHub]]
- [[http://spec.commonmark.org/current/][CommonMark Spec latest]]
- [[http://spec.commonmark.org/dingus/]["Dingus" (live tester)]]

#+BEGIN_EXAMPLE
*strong*

_emphasis_

??citation??

-deleted-

+inserted+

^superscript^

~subscript~

{{monospaced}}

bq. block quoted
#+END_EXAMPLE

** GitHub

[[https://github.github.com/gfm/][GitHub Flavored Markdown Spec]]

GitHub Guide - [[https://guides.github.com/features/mastering-markdown/][Mastering Markdown]]

- [[https://help.github.com/articles/basic-writing-and-formatting-syntax/][GitHub Help Basic writing and formatting syntax]]
- [[https://help.github.com/categories/writing-on-github/][GitHub Help Categories / Writing on GitHub]]
- [[http://kramdown.gettalong.org/][kramdown]]
- [[http://kramdown.gettalong.org/parser/gfm.html][kramdown's gfm parser]]

*** Notify

#+BEGIN_SRC md
@username plz review
#+END_SRC

*** Task List

#+BEGIN_QUOTE
When you include a task list in the first comment of an Issue, you will see a helpful progress bar in your list of issues. It works in Pull Requests, too!
#+END_QUOTE

#+BEGIN_SRC md
- [x] This is a complete item
- [ ] This is an incomplete item
#+END_SRC

** JIRA

[[https://jira.atlassian.com/secure/WikiRendererHelpAction.jspa?section=all][JIRA Text Formatting Notation Help]]

#+BEGIN_EXAMPLE
{{inline-code}}

{code} or {code:javascript}
  return;
{code}

[this site|https://thissite.com]

h1. heading 1

h2. heading 2

bq. one line block quote

{quote}
multiple line
block quote
{quote}

- [or asterisk] ul

# ol
#+END_EXAMPLE

** Markdown

Daring Fireball's:

- [[http://daringfireball.net/projects/markdown/basics][basics]]
- [[http://daringfireball.net/projects/markdown/syntax][syntax]]

** Slack

[[https://get.slack.help/hc/en-us/articles/202288908-Format-your-messages][syntax]] and [[https://api.slack.com/docs/message-formatting][formatting]]

Use single backticks for inline code/monospace, and triple backticks (fencing) for code blocks. Shift+enter for line breaks. Disable markup processing with ~mrkdwn~ set to ~false~:

#+BEGIN_SRC
> to blockquote one paragraph
>>> to blockquote multiple paragraphs
#+END_SRC

#+BEGIN_SRC json
{
  "mrkdwn": false,
  "text": "*This will not be bold.* It will be surrounded gloriously with stars."
}
#+END_SRC

Note: Hyperlinking words and terms in a Slack message isn't supported. [[https://get.slack.help/hc/en-us/articles/204399343-Sharing-links-in-Slack][link]]

** Stack Overflow

Code blocks are four indented spaces.

- Stack Overflow's [[http://stackoverflow.com/editing-help][Markdown help]].

#+BEGIN_SRC
Here's an inline link to [example](http://www.example.com/).

Here's a reference-style link to [example][1].

Here's a very readable link to [example][ddg].

  [1]: https://www.example.com/
  [ddg]: https://www.example.com/
#+END_SRC

* Misc

** Ambiguous Syntax

Markdown difficulty with indented code following lists:

#+BEGIN_SRC md
1.  list item

    This is a paragraph in the list, not indented code.
#+END_SRC

Org-mode with specificity:

#+BEGIN_EXAMPLE
- list

  list paragraph

- list

#+BEGIN_SRC js
code()
#+END_SRC
#+END_EXAMPLE

- list

  list paragraph

- list

#+BEGIN_SRC js
code()
#+END_SRC

ref Meta Stack Exchange [[https://meta.stackexchange.com/questions/3327/code-block-is-not-properly-formatted-when-placed-immediately-after-a-list-item][Code block is not properly formatted when placed immediately after a list item {duplicate}]]
