#+OPTIONS: toc:nil -:nil H:6 ^:nil
#+EXCLUDE_TAGS: no_export
#+BEGIN_EXAMPLE
---
title: "Markup"
layout: notation
description: Wow, Riveting
path: "/markup/"
---
#+END_EXAMPLE

* Quick Syntax Reference

** Basics

#+BEGIN_SRC
| th   | th     | th    |
| :--- | :---:  | ---:  |
| left | middle | right |

*italics*, _alt italics_

**bold**, __alt bold__

***bold italic***, ___alt bold italic___

> quote

~~strike through~~

`code`

[site](example.com)
#+END_SRC


* Dialects, variations

** Chart

| daring fireball          | Slack     | JIRA                   | SO                  |
|--------------------------|-----------|------------------------|---------------------|
| *italics*, _alt italics_ |           |                        |                     |
| __double underscore__    |           |                        |                     |
| **bold**                 |           |                        |                     |
| ***bold italic***        |           |                        |                     |
| > quote                  | >         | {quote}..{quote}       |                     |
| ~~strike through~~       |           |                        |                     |
| `code`                   | `inline`  | {{inline}}             | `inline`            |
| code block               | backticks | {code}..{code}         | indent              |
| [site](example.com)      | n/a       | [site\vertexample.com] | [site](example.com) |

** Markdown

Daring Fireball's:

- [[http://daringfireball.net/projects/markdown/basics][basics]]
- [[http://daringfireball.net/projects/markdown/syntax][syntax]]

** GitHub

[[https://github.github.com/gfm/][gfm spec]]

- [[https://help.github.com/articles/basic-writing-and-formatting-syntax/][syntax]]
- [[https://help.github.com/categories/writing-on-github/][Writing on GitHub]]
- [[http://kramdown.gettalong.org/][Kramdown]]
- [[http://kramdown.gettalong.org/parser/gfm.html][Kramdown parse info]]

** Stack Overflow

Code blocks are four indented spaces.

- Stack Overflow's [[http://stackoverflow.com/editing-help][Markdown help]].

#+BEGIN_SRC
Here's an inline link to [duckduckgo](http://www.duckduckgo.com/).

Here's a reference-style link to [duckduckgo][1].

Here's a very readable link to [duckduckgo][ddg].

  [1]: https://www.duckduckgo.com/
  [ddg]: https://www.duckduckgo.com/
#+END_SRC

** Slack

[[https://get.slack.help/hc/en-us/articles/202288908-Format-your-messages][syntax]] and [[https://api.slack.com/docs/message-formatting][formatting]]

Use single backticks for inline code/monospace, and triple backticks (fencing) for code blocks. Shift+enter for line breaks. Disable markup processing with `mrkdwn` set to `false`:

#+BEGIN_SRC
> to blockquote one paragraph
>>> to blockquote multiple paragraphs
#+END_SRC

#+BEGIN_SRC json
{
  "mrkdwn": false,
  "text": "*This will not be bold.* It will be surrounded gloriously with stars."
}
#+END_SRC

Note: Hyperlinking words and terms in a Slack message isn't supported. [[https://get.slack.help/hc/en-us/articles/204399343-Sharing-links-in-Slack][link]]


** JIRA

[[https://jira.atlassian.com/secure/WikiRendererHelpAction.jspa?section=all][JIRA formatting]]

#+BEGIN_SRC
{{inline-code}}

{code} or {code:javascript}
  return;
{code}

link to [this site|https://thissite.com]

h1. heading 1

h2. heading 2

bq. This is one line of block quote

{quote}
This is multiple lines
of block quote
{quote}

- bullet
- bullet

* also bullet
* also bullet

* numbered
* numbered
#+END_SRC



** CommonMark

An attempt "to specify Markdown syntax unambiguously."

- [[https://github.com/jgm/CommonMark][CommonMark on GitHub]]
- [[http://spec.commonmark.org/0.26/][CommonMark Spec]]
- [[http://spec.commonmark.org/dingus/]["Dingus" (live tester)]]

* Misc

Ambiguity: https://meta.stackexchange.com/a/99637
