---
layout: post
title: "Org"
categories: notation
subtitle: This Pays Off, Right?
---

* Syntax

From <a href="http://orgmode.org/manual/Emphasis-and-monospace.html" target="_blank">the manual</a>:

#+BEGIN_EXAMPLE
*bold*, /italic/, _underlined_, =verbatim= and ~code~, and, if you must, ‘+strike-through+’
#+END_EXAMPLE

* Spreadsheet tables

[[http://orgmode.org/worg/org-tutorials/org-spreadsheet-intro.html][Org as Spreadsheet introduction]]

[[https://emacs.stackexchange.com/a/20506/15295][Helpful SO answer]]

[[http://orgmode.org/manual/Formula-syntax-for-Calc.html#Formula-syntax-for-Calc][Formula Syntax for Calc]]

#+BEGIN_SRC org
:=vsum($2..$3) ;; do a calculation
:=vsum($2..$3);%.2f ;; set format to 2 decimal places
#+END_SRC

| `C-c }`       | show row & column nubmers |
| `C-c {`       | toggle debugging          |
| `C-c C-c`     | "run" at point            |
| `C-c u C-c *` | re-calc table             |


| `::`    | separate formulas                                |
| `$x`    | column number x                                  |
| `@x`    | row number x                                     |
| `@#`    | current row                                      |
| `$#`    | current column                                   |
| `@>`    | last row                                         |
| `x..y`  | range between x and y (top-left to bottom-right) |
| `vsum`  | vector sum                                       |
| `vmean` | average                                          |



* My Project Setup

** Example Tree

This is a sample project code root. It excludes possible additional directories like `config` and `scripts`, and is showing files in `_org`:

#+BEGIN_SRC shell
.
├── _org
│   ├── [project-name].org
│   ├── notes.org
│   ├── scratch.js
│   ├── sitemap.org
├── _reference
├── client/src
│   ├── ...
└── public/dist
    └── ...
#+END_SRC

*** [project-name].org

This contains TODOs. If they should be tracked in the global agenda, then they need to be added to `org-agenda-files`:

#+BEGIN_SRC emacs-lisp
  (setq org-agenda-files (list "~/org/work.org"
                               "~/org/[project-name-1].org"
                               "~/org/[project-name-2].org"
                               "~/org/todo.org"))
#+END_SRC

I symlink this particular file to `~/org/` for easy access, but that's just me.

*** notes.org

When I research something, I'm trying to either learn it or just figure it out to get something done. If it's something that's general or applicable to all of my other projects, I'll try to record the salient bits in the SFSS notations. If it's project-specific, or something I want handy and close by, I'll put it in `notes.org`.

*** sitemap.org

This is optional. Sometimes I write out the sitemap by hand and manually update it as changes occur in order to keep track of what's what, and keep the page names/sections top of mind. In Sunflower Sea Star's case, however, it doesn't make sense to do that for two reasons: one is that since everything roughly a 1-to-1 flat file setup, I can just look at the files in the directory to see what pages are there. Then again, this could be automated and exported, hmmm:

#+BEGIN_SRC shell
echo '-one-off-pages:\n'
echo 'home'
echo 'about\n'
echo '-notations:\n'
ls
#+END_SRC

#+RESULTS:
| -one-off-pages: |
|                 |
| home            |
| about           |
|                 |
| -notations:     |
|                 |
| browsers.md     |
| command-line.md |
| emacs.org       |
| git.md          |
| markdown.md     |
| org.org         |
| server-setup.md |
| system.md       |
| tmux.md         |
| type.md         |
| vim.md          |


* org as spreadsheet

[[https://emacs.stackexchange.com/questions/20498/how-do-i-do-simple-addition-in-org-mode/20506#20506][basics per SO answer]]

[[http://orgmode.org/worg/org-tutorials/org-spreadsheet-intro.html][spreadsheet intro]]

| `C-c ?`           | `org-table-field-info`                         |
| `C-c }`           | `org-table-toggle-coordinate-overlays`         |
| `C-u C-c *`       | reapply formulas                               |
| `:=vmean($2..$3)` | row formula, mean of columns 2 & 3             |
| `=vsum($2..$3)`   | column formula, sum of all rows' columns 2 & 3 |
